- hosts: "{{ FS_MOUNTPOINT }}"
  become: true
  become_user: root
  tasks:  
          - name: Download Letsencrypt
            ignore_errors: yes
            shell: |
               git clone https://github.com/letsencrypt/letsencrypt /opt/package/letsencrypt
               wget https://raw.githubusercontent.com/certbot/certbot/7f0fa18c570942238a7de73ed99945c3710408b4/letsencrypt-auto-source/letsencrypt-auto -O /opt/package/letsencrypt/certbot-auto
               chmod 777 /opt/package/letsencrypt/certbot-auto
               mkdir -p /var/www/letsencrypt/.well-known/acme-challenge/

          - name: Create SSL
            ignore_errors: yes
            shell: |
               yes | /opt/package/letsencrypt/certbot-auto certonly --webroot --agree-tos --no-eff-email --email support@trinix.id -w /var/www/letsencrypt {{ FS_MOUNTPOINT1 }}
