---
- hosts: "{{ FS_MOUNTPOINT }}"
  become: true
  become_user: root
  gather_facts: no
  tasks:

      - name: Install Requirements
        yum:
          name: gcc openssl-devel bzip2-devel libffi-devel zlib-devel xz-devel
          state: present

      - name: Install Python 3.7
        shell: |
          cd /usr/local
          wget https://www.python.org/ftp/python/3.7.11/Python-3.7.11.tgz
          tar xzf Python-3.7.11.tgz
          cd Python-3.7.11
          ./configure --enable-optimizations
          make altinstall
          rm /usr/local/Python-3.7.11.tgz
      
      - name: Install PIP3
        yum:
          name: python3-pip
          state: present
